### ISSUE TITLE
Travis failed build, passes locally

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#127]
https://travis-ci.org/nsoft/jesterj/builds/504075401

This test passes on my laptop, so some ultra-fun time with travis config/docs/etc seems likely...

**Comment by nsoft** [comment]
Passes locally on my macbook, hangs on my ubuntu desktop, probably for unrelated reasons see #128

**Comment by nsoft** [comment]
For whatever reason Travis's environment was allowing the resource checking code in apache http client to detect that the http client in the CloudSolrClient was not closed and that was blowing up. Closing the CloudSolrClient in the test (by deactivating the Plan built in the test) fixed the problem in Commit eb55fa1

**Comment by nsoft** [comment]
This seems to have returned... but I noticed something very strange. The client that's failing is failing at the end of PreanalyzeFieldsTest, but apparently was started as part of StepImplTest?
````
org.jesterj.ingest.processors.PreAnalyzeFieldsTest > classMethod FAILED
    java.lang.AssertionError: ObjectTracker found 1 object(s) that were not released!!! [InternalHttpClient]
    org.apache.solr.common.util.ObjectReleaseTracker$ObjectTrackerException: org.apache.http.impl.client.InternalHttpClient
    	at org.apache.solr.common.util.ObjectReleaseTracker.track(ObjectReleaseTracker.java:42)
    	at org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:321)
    	at org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:330)
    	at org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:268)
    	at org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:255)
    	at org.apache.solr.client.solrj.impl.CloudSolrClient.<init>(CloudSolrClient.java:280)
    	at org.apache.solr.client.solrj.impl.CloudSolrClient$Builder.build(CloudSolrClient.java:1597)
    	at org.jesterj.ingest.processors.SendToSolrCloudProcessor$Builder.build(SendToSolrCloudProcessor.java:272)
    	at org.jesterj.ingest.processors.SendToSolrCloudProcessor$Builder.build(SendToSolrCloudProcessor.java:200)
    	at org.jesterj.ingest.model.impl.StepImpl$Builder.lambda$withProcessor$1(StepImpl.java:581)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at org.jesterj.ingest.model.impl.StepImpl.executeDeferred(StepImpl.java:499)
    	at org.jesterj.ingest.model.impl.StepImpl$Builder.build(StepImpl.java:601)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:306)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.buildStep(PlanImpl.java:299)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at org.jesterj.ingest.model.impl.PlanImpl$Builder.build(PlanImpl.java:276)
    	at org.jesterj.ingest.model.impl.StepImplTest.getPlan(StepImplTest.java:204)
    	at org.jesterj.ingest.model.impl.StepImplTest.testShakespearePlan(StepImplTest.java:120)
````

**Comment by nsoft** [comment]
A clue: I do see this on local builds:
```

org.jesterj.ingest.processors.PreAnalyzeFieldsTest STANDARD_OUT
    2020-05-10T15:05:20,423 INFO SUITE-PreAnalyzeFieldsTest-seed#[382D03BC6BF2A5FE]-worker org.apache.solr.cloud.ZkTestServer Shutting down ZkTestServer.
    2020-05-10T15:05:20,424 INFO SUITE-PreAnalyzeFieldsTest-seed#[382D03BC6BF2A5FE]-worker org.apache.solr.cloud.ZkTestServer waitForServerDown: 127.0.0.1:46655
    2020-05-10T15:05:20,424 INFO SUITE-PreAnalyzeFieldsTest-seed#[382D03BC6BF2A5FE]-worker org.apache.solr.cloud.ZkTestServer parse host and port list: 127.0.0.1:46655
    2020-05-10T15:05:20,424 INFO SUITE-PreAnalyzeFieldsTest-seed#[382D03BC6BF2A5FE]-worker org.apache.solr.cloud.ZkTestServer connecting to 127.0.0.1 46655
    2020-05-10T15:05:20,424 INFO SUITE-PreAnalyzeFieldsTest-seed#[382D03BC6BF2A5FE]-worker org.apache.solr.SolrTestCaseJ4 ------------------------------------------------------- Done waiting for tracked resources to be released

org.jesterj.ingest.processors.PreAnalyzeFieldsTest STANDARD_ERROR
    May 10, 2020 3:05:20 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
    WARNING: Will linger awaiting termination of 1 leaked thread(s).
```
This perhaps implies that the problem is that on the tiny travis machines threads get starved and cleanup takes a long time. (whereas on my 16core/32T desktop things are peachy and cleanup happens in a timely manner.

**Comment by nsoft** [comment]
tweaked travis to run with one process and to use 18.04, we don't need travis builds to be fast, we need them to be reliable.
