### ISSUE TITLE
Upgrade graphviz to avoid JDK version parsing errors

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#136]
https://github.com/nidi3/graphviz-java/issues/69 
Just hit it like this:
````
java.lang.NumberFormatException: For input string: "222-ea"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at guru.nidi.graphviz.engine.GraphvizJdkEngine.<init>(GraphvizJdkEngine.java:28)
	at guru.nidi.graphviz.engine.Graphviz.useDefaultEngines(Graphviz.java:47)
	at guru.nidi.graphviz.engine.Graphviz.getEngine(Graphviz.java:88)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:177)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:70)
	at org.jesterj.ingest.model.impl.PlanImpl.visualize(PlanImpl.java:103)
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:137)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-2" java.lang.NullPointerException
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:181)
	at java.lang.Thread.run(Thread.java:748)
````
````
openjdk version "1.8.0_222-ea"
OpenJDK Runtime Environment (build 1.8.0_222-ea-b03)
OpenJDK 64-Bit Server VM (build 25.222-b03, mixed mode)
````

**Comment by nsoft** [comment]
Upgraded to 0.11.0 but then got an image with this artifact:

![Screenshot from 2019-09-25 09-24-33](https://user-images.githubusercontent.com/3340874/65605001-59f6eb00-df76-11e9-9295-9813bf063f04.png)
