### ISSUE TITLE
Exception when recreating cassandra dirs

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#140]
After rm -rf ~/.jj/cassandra the system should start up fresh as if first install (even if logs dir remains). Observed the following stack trace in this use case:
```

2019-12-23T18:35:53,286 ERROR pool-7-thread-1 org.jesterj.ingest.scanners.SimpleFileScanner Exception while processing files! java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace jj_logging does not exist
	at org.jesterj.ingest.persistence.CassandraSupport.getPreparedQuery(CassandraSupport.java:84)
	at org.jesterj.ingest.model.impl.ScannerImpl.docFound(ScannerImpl.java:245)
	at org.jesterj.ingest.scanners.SimpleFileScanner.makeDoc(SimpleFileScanner.java:167)
	at org.jesterj.ingest.scanners.SimpleFileScanner.access$100(SimpleFileScanner.java:47)
	at org.jesterj.ingest.scanners.SimpleFileScanner$RootWalker.visitFile(SimpleFileScanner.java:107)
	at org.jesterj.ingest.scanners.SimpleFileScanner$RootWalker.visitFile(SimpleFileScanner.java:98)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.jesterj.ingest.scanners.SimpleFileScanner.lambda$getScanOperation$0(SimpleFileScanner.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace jj_logging does not exist
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jesterj.ingest.persistence.CassandraSupport.getPreparedQuery(CassandraSupport.java:82)
	... 13 more
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace jj_logging does not exist
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at org.jesterj.ingest.persistence.CassandraSupport$NonClosableSession.prepare(CassandraSupport.java:159)
	at org.jesterj.ingest.persistence.CassandraSupport.lambda$addStatement$0(CassandraSupport.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jesterj.ingest.persistence.Cassandra.whenBooted(Cassandra.java:173)
	at org.jesterj.ingest.persistence.CassandraSupport.addStatement(CassandraSupport.java:55)
	at org.jesterj.ingest.model.impl.ScannerImpl.<init>(ScannerImpl.java:96)
	at org.jesterj.ingest.scanners.SimpleFileScanner.<init>(SimpleFileScanner.java:56)
	at org.jesterj.ingest.scanners.SimpleFileScanner$Builder.<init>(SimpleFileScanner.java:180)
	at com.customer.ingest.CustomerPlan.getPlan(PubMed.java:75)
	at org.jesterj.ingest.Main.loadJavaConfig(Main.java:259)
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:156)
	... 1 more
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace jj_logging does not exist
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

**Comment by nsoft** [comment]
Some sort of bitrot in the logging stuff... also seeing: 

```
2019-12-23 20:01:01,778 Thread-1 ERROR Error processing element JesterJAppender ([appenders: null]): CLASS_NOT_FOUND
2019-12-23 20:01:01,859 Thread-1 ERROR Unable to locate appender "CASSANDRA" for logger config "org.jesterj"

```

**Comment by nsoft** [comment]
I think this was fixed in the upgrades that lead to JDK 11 support. I've been testing an install and frequently deleting the cassandra files with no difficulty.
