### ISSUE TITLE
Spurious stack traces emenating from Cassandra 4.1

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#169]
Due to https://github.com/nsoft/uno-jar/issues/34 the upgrade to cassandra 4.1 now causes log spam with the following exception:

````
java.lang.NullPointerException
        at com.needhamsoftware.unojar.JarClassLoader.isJarClassLoaderAParent(JarClassLoader.java:482)
        at com.needhamsoftware.unojar.JarClassLoader.loadClass(JarClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.cassandra.service.GCInspector.handleNotification(GCInspector.java:246)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor$ListenerWrapper.handleNotification(DefaultMBeanServerInterceptor.java:1711)
        at java.management/sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:155)
        at jdk.management/com.sun.management.internal.GarbageCollectorExtImpl.createGCNotification(GarbageCollectorExtImpl.java:115)
````
This appears to be harmless but when uno-jar publishes a fix we should upgrade.

**Comment by nsoft** [comment]
fixed in https://github.com/nsoft/jesterj/commit/57d2245baee352a0cd9923db94f93d761a414f7a
