### ISSUE TITLE
Jacoco apparently collecting coverage on JDK

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#71]
Had an email report of this stack trace, which I think probably means Jacoco is trying to do coverage reporting on JDK classes. I suspect this is during test run, but it could be at instrumentation time to... Also interesting that I haven't been running into this locally, but I usually build in IntelliJ so that may effect this.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
	at org.jacoco.agent.rt.internal_5d10cad.PreMain.createRuntime(PreMain.java:51)
	at org.jacoco.agent.rt.internal_5d10cad.PreMain.premain(PreMain.java:43)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.lang.Class.getField(Class.java:1695)
	at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
Process 'Gradle Worker 21' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Worker 21' finished with non-zero exit value 134

**Comment by nsoft** [comment]
I've not seen any further sign of this, closing for now
