### ISSUE TITLE
Strange address problem on startup

### ISSUE THREAD

**Issue by nsoft** [nsoft/jesterj#98]
Something's changed on my computer and now I get this:
```
Listen Address:fd62:832d:3284:0:1c30:4db2:8e6b:c998
2017-10-05T22:57:04,023 ERROR Thread-1 org.apache.cassandra.service.StartupChecks cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
2017-10-05T22:57:19,300 ERROR Thread-1 org.apache.cassandra.service.CassandraDaemon Exception encountered during startup
java.lang.RuntimeException: java.net.BindException: Can't assign requested address
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:745) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:684) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:668) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:774) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:666) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:612) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:393) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]
	at org.jesterj.ingest.persistence.Cassandra.start(Cassandra.java:102) ~[main.jar:1.0-beta1]
	at org.jesterj.ingest.Main.startCassandra(Main.java:188) ~[main.jar:1.0-beta1]
	at org.jesterj.ingest.Main.lambda$main$0(Main.java:122) ~[main.jar:1.0-beta1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_111]
	at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:734) ~[cassandra-all-3.11.0-JJ.jar:3.11.0-SNAPSHOT]

```
I seem to have a rather complicated interface at the listen address but the listen address above doesn't seem to be among the listed addresses....
```
en8: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether 68:5b:35:8c:b4:49 
	inet6 fe80::fd:4ce3:bc48:8c57%en8 prefixlen 64 secured scopeid 0x4 
	inet6 fd62:832d:3284::1098:4562:6556:c13e prefixlen 64 autoconf secured 
	inet6 fd62:832d:3284::79a1:767e:d02e:41be prefixlen 64 deprecated autoconf temporary 
	inet 192.168.2.115 netmask 0xffffff00 broadcast 192.168.2.255
	inet6 fd62:832d:3284::65e2:8c44:15f3:15e4 prefixlen 64 deprecated autoconf temporary 
	inet6 fd62:832d:3284::4504:438c:51a2:f467 prefixlen 64 autoconf temporary 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex,energy-efficient-ethernet>)
	status: active

```

Somehow we're getting something ipv6 not listed on the interface?

**Comment by nsoft** [comment]
Ah this occurs when your interface address changes. Editing ~/.jj/cassandra/cassandra.yml to supply a current address works around the issue. Perhaps trap this and print out a better error message. Maybe, re-run our address picking routine? but then we have to know that we read the yaml and make sure we can't get in an address picking loop if there's some other BindException being thrown...

**Comment by fsparv** [comment]
This bit me again, this time in a demo (because of course you get a new ip on a new wireless network), I'm now annoyed enough to fix it :)
